### ISSUE TITLE
You can add same category that already exist

### ISSUE THREAD

**Issue by nisharg007** [NishargShah/Analyze-Lab#1]
**Describe the bug**
In category section, you can add same category that already exist

**To Reproduce**
1. Go to admin panel
2. Click on category section
3. Click on add category 
4. Add same category that exist already
5. Category added

**Expected behavior**
While adding same category, I expected error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 78

**Comment by NishargShah** [comment]
Solved

**Comment by NishargShah** [comment]
Solved
